version: "3.9"

services:

  frontend:
    build:
      context: .\
      dockerfile: Dockerfile
    container_name: spl_homepage_frontend
    ports:
      - "5173:80"
    restart: always

volumes:
  postgres_data:
